"""Add approved_by field to solution table

Revision ID: 04a81e92bec7
Revises: c4e3ad25a9ec
Create Date: 2025-08-25 12:46:02.906469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a81e92bec7'
down_revision = 'c4e3ad25a9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###
