"""Remove matrix_handle logic from solutions service

Revision ID: 44deb5318b78
Revises: 04a81e92bec7
Create Date: 2025-10-15 04:50:30.532731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44deb5318b78'
down_revision = '04a81e92bec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_column('matrix_handle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matrix_handle', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
