"""initial migration

Revision ID: 79b5d402cbe4
Revises: 
Create Date: 2025-07-18 07:36:47.257188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b5d402cbe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher',
    sa.Column('publisher_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('terraform_modules', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNPUBLISHED', 'PENDING_REVIEW', 'PUBLISHED', name='solutionstatus'), nullable=False),
    sa.Column('platform', sa.Enum('KUBERNETES', 'MACHINE', name='platformtypes'), nullable=False),
    sa.Column('platform_version', sa.JSON(), nullable=True),
    sa.Column('platform_prerequisites', sa.JSON(), nullable=True),
    sa.Column('documentation_main', sa.String(), nullable=True),
    sa.Column('documentation_source', sa.String(), nullable=True),
    sa.Column('get_started_url', sa.String(), nullable=True),
    sa.Column('how_to_operate_url', sa.String(), nullable=True),
    sa.Column('architecture_diagram_url', sa.String(), nullable=True),
    sa.Column('architecture_explanation', sa.Text(), nullable=True),
    sa.Column('submit_bug_url', sa.String(), nullable=True),
    sa.Column('community_discussion_url', sa.String(), nullable=True),
    sa.Column('juju_versions', sa.JSON(), nullable=True),
    sa.Column('publisher_id', sa.String(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='visibility'), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publisher_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'revision', name='_solution_revision_uc')
    )
    op.create_table('charm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charm_name', sa.String(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id', 'charm_name', name='_solution_charm_uc')
    )
    op.create_table('review_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE_REGISTRATION', 'PUBLISH', 'UNPUBLISH', name='revieweractiontype'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solution_maintainer',
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('maintainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maintainer_id'], ['maintainer.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('solution_id', 'maintainer_id')
    )
    op.create_table('use_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useful_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useful_link')
    op.drop_table('use_case')
    op.drop_table('solution_maintainer')
    op.drop_table('review_action')
    op.drop_table('charm')
    op.drop_table('solution')
    op.drop_table('publisher')
    op.drop_table('maintainer')
    # ### end Alembic commands ###
