name: Pack and Deploy

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (Production or Staging)'
        required: true
        type: choice
        options:
          - Production
          - Staging
jobs:
  deploy-staging:
    name: Deploy to Staging
    # Deploy to staging when: pushing to staging branch, pushing to main, or manual dispatch with Staging selected
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main' || github.event.inputs.environment == 'Staging'
    uses: canonical/webteam-devops/.github/workflows/deploy.yaml@main
    with:
      charm_name: ${{ vars.CHARM_NAME }}
      channel: ${{ vars.CHANNEL }}
      juju_controller_name: ${{ vars.JUJU_CONTROLLER_NAME }}
      juju_model_name: ${{ vars.JUJU_MODEL_NAME }}
      environment: "Staging"
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}

  deploy-production:
    name: Deploy to Production
    # Deploy to production only when: pushing to main or manual dispatch with Production selected
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'Production'
    uses: canonical/webteam-devops/.github/workflows/deploy.yaml@main
    with:
      charm_name: ${{ vars.CHARM_NAME }}
      channel: ${{ vars.CHANNEL }}
      juju_controller_name: ${{ vars.JUJU_CONTROLLER_NAME }}
      juju_model_name: ${{ vars.JUJU_MODEL_NAME }}
      environment: "Production"
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
